apps/loyalRyde/urls.py
from django.urls import path, include
from .views_initial import *

# Importar vistas desde las diferentes carpetas
from apps.loyalRyde.views.arrival_views.views import *
from apps.loyalRyde.views.componaie_views.views import *
from apps.loyalRyde.views.departure_views.views import *
from apps.loyalRyde.views.discount_views.views import *
from apps.loyalRyde.views.driver_views.views import *
from apps.loyalRyde.views.fleet_views.views import *
from apps.loyalRyde.views.rates_views.views import *
from apps.loyalRyde.views.zone_rates_views.views import ZoneRatesCreateView, ZoneRatesUpdateView, ZoneRatesDeleteView, ZoneRatesListView
from apps.loyalRyde.views.zones_views.views import ZoneCreateView, ZoneUpdateView, ZonesListView, search_place
from apps.loyalRyde.views.route_views.views import *
from apps.loyalRyde.views.transfers_request_views.views import *
from apps.loyalRyde.views.transfers_request_views.views import get_people_transfer_by_company
from apps.loyalRyde.views.trips_views.views import *
from apps.loyalRyde.views.user_views.views import *

app_name = 'loyalRyde'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('ajax/people-transfer/', get_people_transfer_by_company, name='ajax_people_transfer'),
    path('transfer-request/create/', TransferRequestCreateView.as_view(), name='transfer_request_create'),
    path('transfer-request/guest/', GuestTransferCreateView.as_view(), name='transfer_request_create_guest'),
    path('transfer-request/list/', TransferRequestListView.as_view(), name='transfer_request_list'),
    path('transfer-request/detail/<int:pk>', TransferRequestDetailview.as_view(), name='transfer_request_detail'),
    path('transfer-request/update/<int:pk>', TransferRequestUpdateView.as_view(), name='transfer_request_update'),
    path('users/add/', UserAdd.as_view(), name='user_add'),
    path('users/add_company_user/', UserCompanyAdd.as_view(), name='user_add_company'),
    path('users/list-admin/', UserAdminListView.as_view(), name='user_list_admin'),
    path('users/list-dispatchers/', UserDispatchListView.as_view(), name='user_list_dispatcher'),
    path('users/list-operator/', UserOperatorListView.as_view(), name='user_list_operator'),
    path('users/list-supervisor/', UserSupervisorListView.as_view(), name='user_list_supervisor'),
    path('update/operator/<int:pk>/', UserOperatorUpdateView.as_view(), name='update_user_operator'),
    path('update/supervisor/<int:pk>/', UserSupervisorUpdateView.as_view(), name='update_user_supervisor'),
    path('transfer-request/whatsapp-link/', get_whatsapp_link, name='get_whatsapp_link'),
    # delete user
    path('delete/user/<int:pk>/', DeleteUser.as_view(), name='delete_user'),
    path('company/list/', CompaniesListView.as_view(), name='companies_list'),
    path('company/create/', CompnayAdd.as_view(), name='companies_create'),
    path('drivers/create/', DriverAdd.as_view(), name='driver_add'),
    path('drivers/delete/<int:pk>/', DriverDeleteView.as_view(), name='driver_delete'),
    path('driver/update/<int:pk>/', DriverUpdateView.as_view(), name='driver_update'),
    path('drivers/list/', DriverListView.as_view(), name='driver_list'),
    path('drivers/list/active', DriverActiveListView.as_view(), name='driver_list_active'),
    path('drivers/list/inactive', DriverPendingListView.as_view(), name='driver_list_pending'),
    path('fleet/create/', FleetAdd.as_view(), name='fleet_add'),
    path('fleet/type/create', FleetTypeAdd.as_view(), name='fleet_add_type'),
    path('fleet/type/update/<int:pk>/', FleetTypeUpdateView.as_view(), name='fleet_type_update'),
    path('fleet/list/', FleetListView.as_view(), name='fleet_list'),
    path('fleet/type/list', FleeTypetListView.as_view(), name='fleet_list_type'),
    path('route/create/', RouteCreateView.as_view(), name='route_add'),
    path('route/departure/create', DeparturePointCreateView.as_view(), name='rates_departure_create'),
    path('route/departure/list', DepartureListView.as_view(), name='rates_departure_list'),
    path('route/departure/update/<int:pk>/', DepartureUpdateView.as_view(), name='departure_update'),
    path('route/arrival/create', ArrivalPointCreateView.as_view(), name='rates_arrival_create'),
    path('route/arrival/list', ArrivalListView.as_view(), name='rates_arrival_list'),
    path('route/arrival/update/<int:pk>/', ArrivalPointUpdateView.as_view(), name='arrival_update'),
    path('route/arrival/delete/<int:pk>/', ArrivalPointDeleteView.as_view(), name='arrival_delete'),
    path('route/departure/delete/<int:pk>/', DepartureDeleteView.as_view(), name='departure_delete'),
    path('route/list/', RouteListView.as_view(), name='route_list'),
    path('route/update/<int:pk>/', RouteUpdate.as_view(), name='route_update'),
    path('route/delete/<int:pk>/', RouteDeleteView.as_view(), name='route_delete'),
    path('trips/progress/', TripsProgressListView.as_view(), name='trips_progress'),
    path('trips/completed/', TripsCompletedListView.as_view(), name='trips_completed'),
    path('trips/hold/', TripsHoldListView.as_view(), name='trips_hold'),
    path('trips/approve/', TripsAroveListView.as_view(), name='trips_approve'),
    path('trips/programed/', TripsProgramedListView.as_view(), name='trips_programed'),
    path('trips/cancelled/', TripsCancelledListView.as_view(), name='trips_cancelled'),
    path('rates/list/', RatesListView.as_view(), name='rates_list'),
    path('rates/update/<int:pk>/', RatesUpdateView.as_view(), name='rates_update'),
    path('rates/delete/<int:pk>/', RatesDeleteView.as_view(), name='rates_delete'),
    path('rates/create/', RatesCreateView.as_view(), name='rates_create'),
    # Zone Rates (tarifas por zonas)
    path('zone-rates/list/', ZoneRatesListView.as_view(), name='zone_rates_list'),
    path('zone-rates/create/', ZoneRatesCreateView.as_view(), name='zone_rates_create'),
    path('zone-rates/update/<int:pk>/', ZoneRatesUpdateView.as_view(), name='zone_rates_update'),
    path('zone-rates/delete/<int:pk>/', ZoneRatesDeleteView.as_view(), name='zone_rates_delete'),
    # Zones CRUD + Búsqueda
    path('zones/list/', ZonesListView.as_view(), name='zones_list'),
    path('zones/create/', ZoneCreateView.as_view(), name='zones_create'),
    path('zones/update/<int:pk>/', ZoneUpdateView.as_view(), name='zones_update'),
    path('zones/search/', search_place, name='zones_search'),
    path('discount-coupon/create/', DiscountCouponCreateView.as_view(), name='discount_coupon_create'),
    path('discount-coupons/', DiscountCouponListView.as_view(), name='discount_coupon_list'),
    path('discount-coupon/update/<int:pk>/', DiscountCouponUpdateView.as_view(), name='discount_coupon_update'),
    path('discount-coupon/detail/<int:pk>/', DiscountCouponDetailView.as_view(), name='discount_coupon_detail'),
    path('discount-coupon/delete/', delete_coupon, name='discount_coupon_delete'),
    path('reports/excel/', TransferRequestExcelView.as_view(), name='transfer_request_excel'),
    path('reports/generales/', GeneralReportsView.as_view(), name='reportes_generales'),
    path('reports/company/', FilteredTransferRequestsView.as_view(), name='reports_company'),
    path('transfer/toggle-paid-driver/<int:pk>/', toggle_paid_driver, name='toggle_paid_driver'),

    path('toggle-paid-driver/<int:pk>/', toggle_paid_driver, name='toggle_paid_driver'),
    path('company/update/<int:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    # perfil
    path('profile/', ProfileView.as_view(), name='profile'),
    # perfil
    
    
    # AJAX VIEWS
    path('transfer-request/people/create', get_people_transfer, name='transfer_request_people_create'),
    path('transfer-request/approve', approve_request, name='transfer_request_approve'),
    path('transfer-request/cancel/', cancel_request, name='transfer_request_cancel'),
    path('transfer-request/admin/approve/', approve_request_admin, name='transfer_request_approve_admin'),
    path('company/image', get_company_image, name='company_image'),
    path("transfer-request/routes", get_routes_by_departure, name="routes_ajax"),
    path("transfer-request/rates", get_rates, name="rates_ajax"),
    path('verify-discount-code/', verify_discount_code, name='verify_discount_code'),
    path('ajax/transfer-month/', transfer_requests_per_month, name='transfer_month'),
    path('drivers/payroll/', DriverPayrollView.as_view(), name='driver_payroll'),
    path('drivers/payroll/excel/<int:pk>/', DriverPayrollExcelView.as_view(), name='driver_payroll_excel'),
    path('transfer_request/<int:pk>/pdf/', TransferRequestPDFView.as_view(), name='transfer_request_pdf'),
    path('guest-transfer/success/<int:pk>/', GuestTransferSuccessView.as_view(), name='guest_transfer_success'),
    path('reports/company_filtered/', CompanyFilteredTransferRequestsView.as_view(), name='reports_company_filtered'),
    # Vistas para iniciar y finalizar traslado
    path('transfer/start/', TransferStartView.as_view(), name='transfer_start'),
    path('transfer/finish/', TransferFinishView.as_view(), name='transfer_finish'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1.0/',include('apps.api_app.urls')),
    path('', include('apps.loyalRyde.urls', namespace='core')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/loyal_ryde_system/delete_arrival.html
{% extends "loyal_ryde_system/base/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="post d-flex flex-column-fluid" id="kt_post">
    <div id="kt_content_container" class="container-xxl">
        <div class="card card-flush py-4">
            <div class="card-header">
                <div class="card-title">
                    <h2>{{ title }}</h2>
                </div>
            </div>
            <div class="card-body pt-0">
                <p>{{ text }}</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <a href="{{ url_cancel }}" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/loyal_ryde_system/departure_list.html
{% extends "loyal_ryde_system/base/base.html" %} 
{% load static %} 

{% block title %}Lista de Salidas{% endblock title %}

{% block extra_css %} 
<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>
{% endblock extra_css %}

{% block content %}

<div class="post d-flex flex-column-fluid" id="kt_post" data-aos="zoom-in-up">
    <!--begin::Container-->
    <div id="kt_content_container" class="container-xxl">
        <!--begin::Category-->
        <div class="card card-flush">
            <!--begin::Card header-->
            <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                <!--begin::Card title-->
                <div class="col-md-12 text-center">
                    <h1 class="">Lista de Salidas</h1>
                </div>
                <div class="card-title">
                    <!--begin::Search-->
                    <div class="d-flex align-items-center position-relative my-1">
                        <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                        <span class="svg-icon svg-icon-1 position-absolute ms-4">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                            </svg>
                        </span>
                        <!--end::Svg Icon-->
                        <input type="text" data-kt-ecommerce-category-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Buscar ruta" />
                    </div>
                    <!--end::Search-->
                </div>
                <!--end::Card title-->
                <!--begin::Card toolbar-->
                <div class="card-toolbar">
                    <!--begin::Add customer-->
                    <a href="{% url 'core:rates_departure_create' %}" class="btn btn-primary">Añadir salida</a>
                    <!--end::Add customer-->
                </div>
                <!--end::Card toolbar-->
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body pt-0">
                <!--begin::Table-->
                <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_category_table">
                    <!--begin::Table head-->
                    <thead>
                        <!--begin::Table row-->
                        <tr class="text-start text-gray-850 fw-bolder fs-7 text-uppercase gs-0">
                            <th class="w-10px pe-2">
                                <div class="form-check form-check-sm form-check-custom form-check-solid me-3">
                                    <input class="form-check-input" type="checkbox" data-kt-check="true" data-kt-check-target="#kt_ecommerce_category_table .form-check-input" value="1" />
                                </div>
                            </th>
                            <th class="min-w-250px">Ciudad</th>
                            <th class="min-w-250px">Estado</th>
                            <th class="min-w-150px">Fecha de registro</th>
                            <th class="text-end min-w-70px">Acciones</th>
                        </tr>
                        <!--end::Table row-->
                    </thead>
                    <!--end::Table head-->
                    <!--begin::Table body-->
                    <tbody class="fw-bold text-gray-850">
                        <!--begin::Table row-->
                        {% if departure %}
                            {% for departure in departure %}
                            <tr>
                                <td>
                                    <div class="form-check form-check-sm form-check-custom form-check-solid">
                                        <input class="form-check-input" type="checkbox" value="1" />
                                    </div>
                                </td>   
                                <td>{{ departure.name }}</td>
                                <td>{{ departure.state }}</td>
                                <td>{{ departure.date_created|date:"d/m/Y" }}</td>
                                <td class="text-end">
                                    <a href="#" class="btn btn-light btn-active-light-primary btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Acciones
                                        <span class="svg-icon svg-icon-5 m-0">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor" />
                                            </svg>
                                        </span>
                                    </a>
                                    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" data-kt-menu="true">
                                        <div class="menu-item px-3">
                                            <a href="{% url 'core:departure_update' pk=departure.id %}" class="menu-link px-3">Editar</a>
                                        </div>
                                        <div class="menu-item px-3">
                                            <a href="{% url 'core:departure_delete' pk=departure.id %}" class="menu-link px-3">Eliminar</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                    <!--end::Table body-->
                </table>
                <!--end::Table-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Category-->
    </div>
    <!--end::Container-->
</div>
{% endblock content %} 

{% block extra_js %} 
<script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
<!--end::Page Vendors Javascript-->
<!--begin::Page Custom Javascript(used by this page)-->
<script src="{% static 'assets/js/custom/apps/user-management/users/list/table.js' %}"></script>
<script src="{% static 'assets/js/custom/apps/user-management/users/list/export-users.js' %}"></script>
<script src="{% static 'assets/js/custom/apps/user-management/users/list/add.js' %}"></script>
<script src="{% static 'assets/js/widgets.bundle.js' %}"></script>
<script src="{% static 'assets/js/custom/widgets.js' %}"></script>
<script src="{% static 'assets/js/custom/apps/chat/chat.js' %}"></script>
<script src="{% static 'assets/js/custom/utilities/modals/upgrade-plan.js' %}"></script>
<script src="{% static 'assets/js/custom/utilities/modals/create-app.js' %}"></script>
<script src="{% static 'ssets/js/custom/utilities/modals/users-search.js' %}"></script>
<script>
    $(document).ready(function() {
        var table = $('#kt_ecommerce_category_table').DataTable({
            "paging": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "language": {
                "url": "{% static 'datatables/es.json' %}"
            }
        });
        $('[data-kt-ecommerce-category-filter="search"]').on('keyup', function() {
            table.search(this.value).draw();
        });
    });
</script>
{% endblock extra_js %}

templates/loyal_ryde_system/transfer_request_excel.html
{% extends "loyal_ryde_system/base/base.html" %}
{% load static %}

{% block title %}Traslados Mes 6-2024{% endblock title %}

{% block extra_css %}
<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>
{% endblock extra_css %}

{% block content %}
<div class="post d-flex flex-column-fluid" id="kt_post">
    <div id="kt_content_container" class="container-xxl">
        <div class="card mb-5 mb-xxl-12">
            <div class="card-body">
                <div class="col-md-12 text-center pb-0">
                    <h1>Lista de traslados Transporte GGMN - Mes 6-2024</h1>
                </div>
                <div class="mb-10 pt-9">
                    <div class="table-responsive">
                        <table class="table table-rounded table-striped border gy-7 gs-7" id="transfer_list_table">
                            <thead>
                                <tr class="fw-bold fs-6 text-gray-800 border-bottom border-gray-200">
                                    <th>Fecha</th>
                                    <th>Hora</th>
                                    <!-- <th>Pasajero</th> -->
                                    <th>Origen</th>
                                    <th>Destino</th>
                                    <!-- <th>Descripcion</th> -->
                                    <th>Monto base $</th>
                                    <th>Tiempo de espera</th>
                                    <th>Desvios</th>
                                    <!-- <th>Lugar</th> -->
                                    <th>Monto total $</th>
                                    <th>GRAFO/CECO</th>
                                    <th>Solicitante</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for transfer_request in transfer_requests %}
                                    <tr>
                                        <td class="text-center">{{ transfer_request.date|date:'d/m/Y' }}</td>
                                        <td class="text-center">{{ transfer_request.hour|date:'G:i' }}</td>
                                        <!-- <td class="text-center">{{ transfer_request.passenger.name }}</td> -->
                                        <td class="text-center">{{ transfer_request.departure_site_route }}</td>
                                        <td class="text-center">{{ transfer_request.destination_route }}</td>
                                        <!-- <td class="text-center">{{ transfer_request.description }}</td> -->
                                        <td class="text-center">{{ transfer_request.waiting_hours_count }}</td>
                                        <td class="text-center">{{ transfer_request.waiting_hours_amount }}</td>
                                        <td class="text-center">{{ transfer_request.diversions_count }}</td>
                                        <!-- <td class="text-center">{{ transfer_request.diversion_place }}</td> -->
                                        <td class="text-center">{{ transfer_request.total_transfer_amount }}</td>
                                        <td class="text-center">{{ transfer_request.grafo_ceco }}</td>
                                        <td class="text-center">{{ transfer_request.service_requested.company.name }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>                            
                    </div>
                </div>
                <div class="text-center">
                    <button id="export-btn" class="btn btn-primary">Exportar a Excel</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#transfer_list_table').DataTable();

        $('#export-btn').click(function() {
            $.ajax({
                url: "{% url 'core:transfer_request_excel' %}?export=true",
                method: 'GET',
                xhrFields: {
                    responseType: 'blob'
                },
                success: function(data) {
                    var a = document.createElement('a');
                    var url = window.URL.createObjectURL(data);
                    a.href = url;
                    a.download = 'solicitud_traslados_mes_6_2024.xlsx';
                    document.body.append(a);
                    a.click();
                    a.remove();
                    window.URL.revokeObjectURL(url);
                },
                error: function() {
                    alert('Error al exportar el archivo.');
                }
            });
        });
    });
</script>
{% endblock extra_js %}

templates/loyal_ryde_system/zone_rates.html
{% extends "loyal_ryde_system/base/base.html" %} 
{% load static %} 

{% block title %}Lista de Tarifas de Zona{% endblock title %}

{% block extra_css %} 

<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
{% endblock extra_css %}

{% block content %}

<div class="post d-flex flex-column-fluid" id="kt_post" data-aos="fade-left">
  <div id="kt_content_container" class="container-xxl">
    <div class="card card-flush">
      <div class="card-header align-items-center py-5 gap-2 gap-md-5">
        <div class="col-md-12 text-center">
          <h1 class="">Lista de Tarifas de Zona</h1>
        </div>
        <div class="card-title">
          <div class="d-flex align-items-center position-relative my-1">
            <span class="svg-icon svg-icon-1 position-absolute ms-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
              </svg>
            </span>
            <input type="text" data-kt-ecommerce-category-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Buscar tarifa" />
          </div>
        </div>
        <div class="ms-auto">
          <a href="{% url 'core:zone_rates_create' %}" class="btn btn-sm btn-primary">Nueva Tarifa de Zona</a>
        </div>
      </div>
      <div class="card-body pt-0">
        <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_zone_rates_table">
          <thead>
            <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
              <th class="w-10px pe-2">
                <div class="form-check form-check-sm form-check-custom form-check-solid me-3">
                  <input class="form-check-input" type="checkbox" data-kt-check="true" data-kt-check-target="#kt_zone_rates_table .form-check-input" value="1" />
                </div>
              </th>
              <th class="">Zonas</th>
              <th class="">Tipo de vehiculo</th>
              <th class="">Precio Ida ($)</th>
              <th class="">precio Ida y vuelta ($)</th>
              <th>Ganancia del Conductor (%)</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody class="fw-bold text-gray-600">
            {% for zr in zone_rates %}
            <tr>
              <td>
                <div class="form-check form-check-sm form-check-custom form-check-solid">
                  <input class="form-check-input" type="checkbox" value="1" />
                </div>
              </td>
              <td>
                <div>
                  {{ zr.origin.name }} → {{ zr.destination.name }}
                </div>
              </td>
              <td>
                <div>
                  {{ zr.type_vehicle.type|default:"N/A" }}
                </div>
              </td>
              <td><div>{{ zr.price }}$</div></td>
              <td><div>{{ zr.price_round_trip }}$</div></td>
              <td><div>{{ zr.driver_gain }}%</div></td>
              <td class="text-end">
                <a href="#" class="btn btn-light btn-active-light-primary btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Acciones
                <span class="svg-icon svg-icon-5 m-0">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                    <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor" />
                  </svg>
                </span></a>
                <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" data-kt-menu="true">
                  <div class="menu-item px-3">
                    <a href="{% url 'core:zone_rates_update' pk=zr.pk %}" class="menu-link px-3">Editar</a>
                  </div>
                  <div class="menu-item px-3">
                    <a href="{% url 'core:zone_rates_delete' pk=zr.pk %}" class="menu-link px-3" data-kt-users-table-filter="delete_row">Eliminar</a>
                  </div>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %} 

{% block extra_js %}
<script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script>
  $(document).ready(function() {
    var table = $('#kt_zone_rates_table').DataTable({
      paging: true,
      searching: true,
      ordering: true,
      info: true,
      language: { url: "{% static 'datatables/es.json' %}" }
    });
    $('[data-kt-ecommerce-category-filter="search"]').on('keyup', function() {
      table.search(this.value).draw();
    });
  });
</script>
{% endblock extra_js %}