apps/loyalRyde/urls.py
from django.urls import path, include
from .views_initial import *

# Importar vistas desde las diferentes carpetas
from apps.loyalRyde.views.arrival_views.views import *
from apps.loyalRyde.views.componaie_views.views import *
from apps.loyalRyde.views.departure_views.views import *
from apps.loyalRyde.views.discount_views.views import *
from apps.loyalRyde.views.driver_views.views import *
from apps.loyalRyde.views.fleet_views.views import *
from apps.loyalRyde.views.rates_views.views import *
from apps.loyalRyde.views.zone_rates_views.views import ZoneRatesCreateView, ZoneRatesUpdateView, ZoneRatesDeleteView, ZoneRatesListView
from apps.loyalRyde.views.zones_views.views import ZoneCreateView, ZoneUpdateView, ZonesListView, search_place
from apps.loyalRyde.views.route_views.views import *
from apps.loyalRyde.views.transfers_request_views.views import *
from apps.loyalRyde.views.transfers_request_views.views import get_people_transfer_by_company
from apps.loyalRyde.views.trips_views.views import *
from apps.loyalRyde.views.user_views.views import *

app_name = 'loyalRyde'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('ajax/people-transfer/', get_people_transfer_by_company, name='ajax_people_transfer'),
    path('transfer-request/create/', TransferRequestCreateView.as_view(), name='transfer_request_create'),
    path('transfer-request/guest/', GuestTransferCreateView.as_view(), name='transfer_request_create_guest'),
    path('transfer-request/list/', TransferRequestListView.as_view(), name='transfer_request_list'),
    path('transfer-request/detail/<int:pk>', TransferRequestDetailview.as_view(), name='transfer_request_detail'),
    path('transfer-request/update/<int:pk>', TransferRequestUpdateView.as_view(), name='transfer_request_update'),
    path('users/add/', UserAdd.as_view(), name='user_add'),
    path('users/add_company_user/', UserCompanyAdd.as_view(), name='user_add_company'),
    path('users/list-admin/', UserAdminListView.as_view(), name='user_list_admin'),
    path('users/list-dispatchers/', UserDispatchListView.as_view(), name='user_list_dispatcher'),
    path('users/list-operator/', UserOperatorListView.as_view(), name='user_list_operator'),
    path('users/list-supervisor/', UserSupervisorListView.as_view(), name='user_list_supervisor'),
    path('update/operator/<int:pk>/', UserOperatorUpdateView.as_view(), name='update_user_operator'),
    path('update/supervisor/<int:pk>/', UserSupervisorUpdateView.as_view(), name='update_user_supervisor'),
    path('transfer-request/whatsapp-link/', get_whatsapp_link, name='get_whatsapp_link'),
    # delete user
    path('delete/user/<int:pk>/', DeleteUser.as_view(), name='delete_user'),
    path('company/list/', CompaniesListView.as_view(), name='companies_list'),
    path('company/create/', CompnayAdd.as_view(), name='companies_create'),
    path('drivers/create/', DriverAdd.as_view(), name='driver_add'),
    path('drivers/delete/<int:pk>/', DriverDeleteView.as_view(), name='driver_delete'),
    path('driver/update/<int:pk>/', DriverUpdateView.as_view(), name='driver_update'),
    path('drivers/list/', DriverListView.as_view(), name='driver_list'),
    path('drivers/list/active', DriverActiveListView.as_view(), name='driver_list_active'),
    path('drivers/list/inactive', DriverPendingListView.as_view(), name='driver_list_pending'),
    path('fleet/create/', FleetAdd.as_view(), name='fleet_add'),
    path('fleet/type/create', FleetTypeAdd.as_view(), name='fleet_add_type'),
    path('fleet/type/update/<int:pk>/', FleetTypeUpdateView.as_view(), name='fleet_type_update'),
    path('fleet/list/', FleetListView.as_view(), name='fleet_list'),
    path('fleet/type/list', FleeTypetListView.as_view(), name='fleet_list_type'),
    path('route/create/', RouteCreateView.as_view(), name='route_add'),
    path('route/departure/create', DeparturePointCreateView.as_view(), name='rates_departure_create'),
    path('route/departure/list', DepartureListView.as_view(), name='rates_departure_list'),
    path('route/departure/update/<int:pk>/', DepartureUpdateView.as_view(), name='departure_update'),
    path('route/arrival/create', ArrivalPointCreateView.as_view(), name='rates_arrival_create'),
    path('route/arrival/list', ArrivalListView.as_view(), name='rates_arrival_list'),
    path('route/arrival/update/<int:pk>/', ArrivalPointUpdateView.as_view(), name='arrival_update'),
    path('route/arrival/delete/<int:pk>/', ArrivalPointDeleteView.as_view(), name='arrival_delete'),
    path('route/departure/delete/<int:pk>/', DepartureDeleteView.as_view(), name='departure_delete'),
    path('route/list/', RouteListView.as_view(), name='route_list'),
    path('route/update/<int:pk>/', RouteUpdate.as_view(), name='route_update'),
    path('route/delete/<int:pk>/', RouteDeleteView.as_view(), name='route_delete'),
    path('trips/progress/', TripsProgressListView.as_view(), name='trips_progress'),
    path('trips/completed/', TripsCompletedListView.as_view(), name='trips_completed'),
    path('trips/hold/', TripsHoldListView.as_view(), name='trips_hold'),
    path('trips/approve/', TripsAroveListView.as_view(), name='trips_approve'),
    path('trips/programed/', TripsProgramedListView.as_view(), name='trips_programed'),
    path('trips/cancelled/', TripsCancelledListView.as_view(), name='trips_cancelled'),
    path('rates/list/', RatesListView.as_view(), name='rates_list'),
    path('rates/update/<int:pk>/', RatesUpdateView.as_view(), name='rates_update'),
    path('rates/delete/<int:pk>/', RatesDeleteView.as_view(), name='rates_delete'),
    path('rates/create/', RatesCreateView.as_view(), name='rates_create'),
    # Zone Rates (tarifas por zonas)
    path('zone-rates/list/', ZoneRatesListView.as_view(), name='zone_rates_list'),
    path('zone-rates/create/', ZoneRatesCreateView.as_view(), name='zone_rates_create'),
    path('zone-rates/update/<int:pk>/', ZoneRatesUpdateView.as_view(), name='zone_rates_update'),
    path('zone-rates/delete/<int:pk>/', ZoneRatesDeleteView.as_view(), name='zone_rates_delete'),
    # Zones CRUD + Búsqueda
    path('zones/list/', ZonesListView.as_view(), name='zones_list'),
    path('zones/create/', ZoneCreateView.as_view(), name='zones_create'),
    path('zones/update/<int:pk>/', ZoneUpdateView.as_view(), name='zones_update'),
    path('zones/search/', search_place, name='zones_search'),
    path('discount-coupon/create/', DiscountCouponCreateView.as_view(), name='discount_coupon_create'),
    path('discount-coupons/', DiscountCouponListView.as_view(), name='discount_coupon_list'),
    path('discount-coupon/update/<int:pk>/', DiscountCouponUpdateView.as_view(), name='discount_coupon_update'),
    path('discount-coupon/detail/<int:pk>/', DiscountCouponDetailView.as_view(), name='discount_coupon_detail'),
    path('discount-coupon/delete/', delete_coupon, name='discount_coupon_delete'),
    path('reports/excel/', TransferRequestExcelView.as_view(), name='transfer_request_excel'),
    path('reports/generales/', GeneralReportsView.as_view(), name='reportes_generales'),
    path('reports/company/', FilteredTransferRequestsView.as_view(), name='reports_company'),
    path('transfer/toggle-paid-driver/<int:pk>/', toggle_paid_driver, name='toggle_paid_driver'),

    path('toggle-paid-driver/<int:pk>/', toggle_paid_driver, name='toggle_paid_driver'),
    path('company/update/<int:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    # perfil
    path('profile/', ProfileView.as_view(), name='profile'),
    # perfil
    
    
    # AJAX VIEWS
    path('transfer-request/people/create', get_people_transfer, name='transfer_request_people_create'),
    path('transfer-request/approve', approve_request, name='transfer_request_approve'),
    path('transfer-request/cancel/', cancel_request, name='transfer_request_cancel'),
    path('transfer-request/admin/approve/', approve_request_admin, name='transfer_request_approve_admin'),
    path('company/image', get_company_image, name='company_image'),
    path("transfer-request/routes", get_routes_by_departure, name="routes_ajax"),
    path("transfer-request/rates", get_rates, name="rates_ajax"),
    path('verify-discount-code/', verify_discount_code, name='verify_discount_code'),
    path('ajax/transfer-month/', transfer_requests_per_month, name='transfer_month'),
    path('drivers/payroll/', DriverPayrollView.as_view(), name='driver_payroll'),
    path('drivers/payroll/excel/<int:pk>/', DriverPayrollExcelView.as_view(), name='driver_payroll_excel'),
    path('transfer_request/<int:pk>/pdf/', TransferRequestPDFView.as_view(), name='transfer_request_pdf'),
    path('guest-transfer/success/<int:pk>/', GuestTransferSuccessView.as_view(), name='guest_transfer_success'),
    path('reports/company_filtered/', CompanyFilteredTransferRequestsView.as_view(), name='reports_company_filtered'),
    # Vistas para iniciar y finalizar traslado
    path('transfer/start/', TransferStartView.as_view(), name='transfer_start'),
    path('transfer/finish/', TransferFinishView.as_view(), name='transfer_finish'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1.0/',include('apps.api_app.urls')),
    path('', include('apps.loyalRyde.urls', namespace='core')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/loyal_ryde_system/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<!--begin::Head-->

<head>
	<base href="../" />
	<title>Loyal Ride {% block title %}{% endblock title %}</title>
	<meta charset="utf-8" />
	<meta name="description" content="Sistema de administración LOYAL RIDE" />
	<meta name="keywords" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta property="og:locale" content="es_ES" />
	<link rel="shortcut icon" href="{% static 'assets/media/logos/favicon.ico'%}" />

	<link href="{% static 'assets/css/custom.css'%}" rel="stylesheet" type="text/css" />

	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />

	<!--begin::Global Stylesheets Bundle(used by all pages)-->
	<link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
	<link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
	<link href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css" rel="stylesheet">
	<style>
		.font_white {
			color: white
		}
	</style>
	<!--end::Global Stylesheets Bundle-->
	{% block extra_css %} {% endblock extra_css %}
</head>
<!--end::Head-->
<!--begin::Body-->

<body id="kt_body" class="header-fixed header-tablet-and-mobile-fixed toolbar-enabled aside-enabled aside-fixed" style="
			--kt-toolbar-height: 55px;
			--kt-toolbar-height-tablet-and-mobile: 55px;
		">
	<!--begin::Main-->
	<!--begin::Root-->
	<div class="d-flex flex-column flex-root">
		<!--begin::Page-->
		<div class="page d-flex flex-row flex-column-fluid">
			<!--begin::Aside-->
			{% include "loyal_ryde_system/base/sidebar.html" %}
			<!--end::Aside-->
			<!--begin::Wrapper-->
			<div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">
				<!--begin::Header-->
				{% include "loyal_ryde_system/base/topbar.html" %}
				<!--end::Header-->

				{% block toolbar %}
				{% include "loyal_ryde_system/base/toolbar.html" %}
				{% endblock toolbar %}

				<!--begin::Content-->
				{% block content %} {% endblock content %}
				<!--end::Content-->
				<!--begin::Footer-->

				<!--end::Footer-->
			</div>

		<!--begin::Javascript-->
		</div>
		<!--end::Page-->
	</div>
	{% include "loyal_ryde_system/base/topbar_left.html" %}

	<!--begin::Javascript-->
	<script>
		var hostUrl = "{% static 'assets/' %}";
	</script>
	<!--begin::Global Javascript Bundle(used by all pages)-->
	<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
	<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
	<script src="{% static 'assets/js/sweetalert2/sweet-alert-2-11.js'%}"></script>
	<!-- AOS Animate On Scroll JS -->
	<script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
	<script>
		AOS.init();
	</script>
	<!-- <script>
			{% if messages %}
				var success_message = '';
				{% for message in messages %}
					success_message += '<p style="margin-top: 7px; margin-bottom: 7px;">{{ message }}</p>';
				{% endfor %}
				Swal.fire({
					title: 'Éxito!',
					html: success_message, // Cambia 'text' por 'html'
					icon: "success",
					width: 500,
					heigth: 700
				});
			{% endif %}
		</script> -->
	{% block error_js %}
	<script>
		{% if form.errors %}
		var errors = '';
		{% for field in form %}
		{% for error in field.errors %}
		errors += '<p style="margin-top: 7px; margin-bottom: 7px;">{{ field.label|title }}: {{ error }}</p>';
		{% endfor %}
		{% endfor %}
		Swal.fire({
			title: 'Error!',
			html: errors, // Cambia 'text' por 'html'
			icon: "error",
			width: 500,
			height: 700
			// footer: '<a href="#">Why do I have this issue?</a>'
		});
		{% endif %}
	</script>
	{% endblock error_js %}
	{% if messages %}
	<script>
		Swal.fire({
			icon: 'success',
			title: 'Éxito',
			html: '{% for message in messages %}<p>{{ message }}</p>{% endfor %}',
			showConfirmButton: true,
			confirmButtonText: 'Cerrar'
		});
	</script>
	{% endif %}
	<!--end::Global Javascript Bundle-->
	{% block extra_js %} {% endblock extra_js %}
	<!--end::Javascript-->
</body>
<!--end::Body-->

</html>

templates/loyal_ryde_system/base/footer.html
<div class="footer py-4 d-flex flex-lg-column transparente1" id="kt_footer">
	<!--begin::Container-->
	<div
		class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between"
	>
		<!--begin::Copyright-->
		<div class="text-dark order-2 order-md-1">
			<span class="text-muted fw-bold me-1">2024</span>
			<a
				href="#"
				target="_blank"
				class="text-gray-800 text-hover-primary"
				>Transportes GGMN</a
			>
		</div>
		<!--end::Copyright-->
 
	</div>
	<!--end::Container-->
</div>

templates/loyal_ryde_system/base/toolbar.html
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Toolbar-->
    <div class="toolbar" id="kt_toolbar">
        <!--begin::Container-->
        <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}" class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
                <!--begin::Title-->
                <h1 class="d-flex text-dark fw-bolder fs-3 align-items-center my-1">LOYAL RIDE</h1>
                <!--end::Title-->
                <!--begin::Separator-->
                <span class="h-20px border-gray-300 border-start mx-4"></span>
                <!--end::Separator-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-muted">
                        <a href="{% url 'core:index' %}" class="text-muted text-hover-primary">Inicio</a>
                    </li>
                    <!-- <li class="breadcrumb-item">
                        <span class="bullet bg-gray-300 w-5px h-2px"></span>
                    </li>
                    <li class="breadcrumb-item text-muted">Pages</li>
                     -->
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <!--end::Actions-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Toolbar-->