apps/loyalRyde/urls.py
from django.urls import path, include
from .views_initial import *

# Importar vistas desde las diferentes carpetas
from apps.loyalRyde.views.arrival_views.views import *
from apps.loyalRyde.views.componaie_views.views import *
from apps.loyalRyde.views.departure_views.views import *
from apps.loyalRyde.views.discount_views.views import *
from apps.loyalRyde.views.driver_views.views import *
from apps.loyalRyde.views.fleet_views.views import *
from apps.loyalRyde.views.rates_views.views import *
from apps.loyalRyde.views.zone_rates_views.views import ZoneRatesCreateView, ZoneRatesUpdateView, ZoneRatesDeleteView, ZoneRatesListView
from apps.loyalRyde.views.zones_views.views import ZoneCreateView, ZoneUpdateView, ZonesListView, search_place
from apps.loyalRyde.views.route_views.views import *
from apps.loyalRyde.views.transfers_request_views.views import *
from apps.loyalRyde.views.transfers_request_views.views import get_people_transfer_by_company
from apps.loyalRyde.views.trips_views.views import *
from apps.loyalRyde.views.user_views.views import *

app_name = 'loyalRyde'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('ajax/people-transfer/', get_people_transfer_by_company, name='ajax_people_transfer'),
    path('transfer-request/create/', TransferRequestCreateView.as_view(), name='transfer_request_create'),
    path('transfer-request/guest/', GuestTransferCreateView.as_view(), name='transfer_request_create_guest'),
    path('transfer-request/list/', TransferRequestListView.as_view(), name='transfer_request_list'),
    path('transfer-request/detail/<int:pk>', TransferRequestDetailview.as_view(), name='transfer_request_detail'),
    path('transfer-request/update/<int:pk>', TransferRequestUpdateView.as_view(), name='transfer_request_update'),
    path('users/add/', UserAdd.as_view(), name='user_add'),
    path('users/add_company_user/', UserCompanyAdd.as_view(), name='user_add_company'),
    path('users/list-admin/', UserAdminListView.as_view(), name='user_list_admin'),
    path('users/list-dispatchers/', UserDispatchListView.as_view(), name='user_list_dispatcher'),
    path('users/list-operator/', UserOperatorListView.as_view(), name='user_list_operator'),
    path('users/list-supervisor/', UserSupervisorListView.as_view(), name='user_list_supervisor'),
    path('update/operator/<int:pk>/', UserOperatorUpdateView.as_view(), name='update_user_operator'),
    path('update/supervisor/<int:pk>/', UserSupervisorUpdateView.as_view(), name='update_user_supervisor'),
    path('transfer-request/whatsapp-link/', get_whatsapp_link, name='get_whatsapp_link'),
    # delete user
    path('delete/user/<int:pk>/', DeleteUser.as_view(), name='delete_user'),
    path('company/list/', CompaniesListView.as_view(), name='companies_list'),
    path('company/create/', CompnayAdd.as_view(), name='companies_create'),
    path('drivers/create/', DriverAdd.as_view(), name='driver_add'),
    path('drivers/delete/<int:pk>/', DriverDeleteView.as_view(), name='driver_delete'),
    path('driver/update/<int:pk>/', DriverUpdateView.as_view(), name='driver_update'),
    path('drivers/list/', DriverListView.as_view(), name='driver_list'),
    path('drivers/list/active', DriverActiveListView.as_view(), name='driver_list_active'),
    path('drivers/list/inactive', DriverPendingListView.as_view(), name='driver_list_pending'),
    path('fleet/create/', FleetAdd.as_view(), name='fleet_add'),
    path('fleet/type/create', FleetTypeAdd.as_view(), name='fleet_add_type'),
    path('fleet/type/update/<int:pk>/', FleetTypeUpdateView.as_view(), name='fleet_type_update'),
    path('fleet/list/', FleetListView.as_view(), name='fleet_list'),
    path('fleet/type/list', FleeTypetListView.as_view(), name='fleet_list_type'),
    path('route/create/', RouteCreateView.as_view(), name='route_add'),
    path('route/departure/create', DeparturePointCreateView.as_view(), name='rates_departure_create'),
    path('route/departure/list', DepartureListView.as_view(), name='rates_departure_list'),
    path('route/departure/update/<int:pk>/', DepartureUpdateView.as_view(), name='departure_update'),
    path('route/arrival/create', ArrivalPointCreateView.as_view(), name='rates_arrival_create'),
    path('route/arrival/list', ArrivalListView.as_view(), name='rates_arrival_list'),
    path('route/arrival/update/<int:pk>/', ArrivalPointUpdateView.as_view(), name='arrival_update'),
    path('route/arrival/delete/<int:pk>/', ArrivalPointDeleteView.as_view(), name='arrival_delete'),
    path('route/departure/delete/<int:pk>/', DepartureDeleteView.as_view(), name='departure_delete'),
    path('route/list/', RouteListView.as_view(), name='route_list'),
    path('route/update/<int:pk>/', RouteUpdate.as_view(), name='route_update'),
    path('route/delete/<int:pk>/', RouteDeleteView.as_view(), name='route_delete'),
    path('trips/progress/', TripsProgressListView.as_view(), name='trips_progress'),
    path('trips/completed/', TripsCompletedListView.as_view(), name='trips_completed'),
    path('trips/hold/', TripsHoldListView.as_view(), name='trips_hold'),
    path('trips/approve/', TripsAroveListView.as_view(), name='trips_approve'),
    path('trips/programed/', TripsProgramedListView.as_view(), name='trips_programed'),
    path('trips/cancelled/', TripsCancelledListView.as_view(), name='trips_cancelled'),
    path('rates/list/', RatesListView.as_view(), name='rates_list'),
    path('rates/update/<int:pk>/', RatesUpdateView.as_view(), name='rates_update'),
    path('rates/delete/<int:pk>/', RatesDeleteView.as_view(), name='rates_delete'),
    path('rates/create/', RatesCreateView.as_view(), name='rates_create'),
    # Zone Rates (tarifas por zonas)
    path('zone-rates/list/', ZoneRatesListView.as_view(), name='zone_rates_list'),
    path('zone-rates/create/', ZoneRatesCreateView.as_view(), name='zone_rates_create'),
    path('zone-rates/update/<int:pk>/', ZoneRatesUpdateView.as_view(), name='zone_rates_update'),
    path('zone-rates/delete/<int:pk>/', ZoneRatesDeleteView.as_view(), name='zone_rates_delete'),
    # Zones CRUD + Búsqueda
    path('zones/list/', ZonesListView.as_view(), name='zones_list'),
    path('zones/create/', ZoneCreateView.as_view(), name='zones_create'),
    path('zones/update/<int:pk>/', ZoneUpdateView.as_view(), name='zones_update'),
    path('zones/search/', search_place, name='zones_search'),
    path('discount-coupon/create/', DiscountCouponCreateView.as_view(), name='discount_coupon_create'),
    path('discount-coupons/', DiscountCouponListView.as_view(), name='discount_coupon_list'),
    path('discount-coupon/update/<int:pk>/', DiscountCouponUpdateView.as_view(), name='discount_coupon_update'),
    path('discount-coupon/detail/<int:pk>/', DiscountCouponDetailView.as_view(), name='discount_coupon_detail'),
    path('discount-coupon/delete/', delete_coupon, name='discount_coupon_delete'),
    path('reports/excel/', TransferRequestExcelView.as_view(), name='transfer_request_excel'),
    path('reports/generales/', GeneralReportsView.as_view(), name='reportes_generales'),
    path('reports/company/', FilteredTransferRequestsView.as_view(), name='reports_company'),
    path('transfer/toggle-paid-driver/<int:pk>/', toggle_paid_driver, name='toggle_paid_driver'),

    path('toggle-paid-driver/<int:pk>/', toggle_paid_driver, name='toggle_paid_driver'),
    path('company/update/<int:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    # perfil
    path('profile/', ProfileView.as_view(), name='profile'),
    # perfil
    
    
    # AJAX VIEWS
    path('transfer-request/people/create', get_people_transfer, name='transfer_request_people_create'),
    path('transfer-request/approve', approve_request, name='transfer_request_approve'),
    path('transfer-request/cancel/', cancel_request, name='transfer_request_cancel'),
    path('transfer-request/admin/approve/', approve_request_admin, name='transfer_request_approve_admin'),
    path('company/image', get_company_image, name='company_image'),
    path("transfer-request/routes", get_routes_by_departure, name="routes_ajax"),
    path("transfer-request/rates", get_rates, name="rates_ajax"),
    path('verify-discount-code/', verify_discount_code, name='verify_discount_code'),
    path('ajax/transfer-month/', transfer_requests_per_month, name='transfer_month'),
    path('drivers/payroll/', DriverPayrollView.as_view(), name='driver_payroll'),
    path('drivers/payroll/excel/<int:pk>/', DriverPayrollExcelView.as_view(), name='driver_payroll_excel'),
    path('transfer_request/<int:pk>/pdf/', TransferRequestPDFView.as_view(), name='transfer_request_pdf'),
    path('guest-transfer/success/<int:pk>/', GuestTransferSuccessView.as_view(), name='guest_transfer_success'),
    path('reports/company_filtered/', CompanyFilteredTransferRequestsView.as_view(), name='reports_company_filtered'),
    # Vistas para iniciar y finalizar traslado
    path('transfer/start/', TransferStartView.as_view(), name='transfer_start'),
    path('transfer/finish/', TransferFinishView.as_view(), name='transfer_finish'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1.0/',include('apps.api_app.urls')),
    path('', include('apps.loyalRyde.urls', namespace='core')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/loyal_ryde_system/trips/trips_approve.html
{% extends "loyal_ryde_system/base/base.html" %} 
{% load static %} 

{% block title %}Lista de Viajes{% endblock title %}

{% block extra_css %} 

<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
{% endblock extra_css %}

{% block content %}

<div class="post d-flex flex-column-fluid" id="kt_post" data-aos="fade-right">
    <!--begin::Container-->
    <div id="kt_content_container" class="container-xxl">
        <!--begin::Category-->
        <div class="card card-flush">
            <!--begin::Card header-->
            <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                <!--begin::Card title-->
                
                <div class="col-md-12 text-center">
                    <h1 class="">Lista de Viajes: Aprobados</h1>
                </div>
                <div class="card-title">
                    <!--begin::Search-->
                    <div class="d-flex align-items-center position-relative my-1">
                        <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                        <span class="svg-icon svg-icon-1 position-absolute ms-4">
                            <svg xmlns="http://www.w3.org/------00/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                            </svg>
                        </span>
                        <!--end::Svg Icon-->
                        <input type="text" data-kt-ecommerce-category-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Buscar viaje" />
                    </div>
                    <!--end::Search-->
                </div>
                <!--end::Card title-->
                <!--begin::Card toolbar-->
                <!--end::Card toolbar-->
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body pt-0">
                <!--begin::Table-->
                
                <table class="table table-rounded table-striped border gy-7 gs-7" id="transfer_list_table">
                    <thead>
                        <tr class="fw-bold fs-6 text-gray-800 border-bottom border-gray-200">
                            <th>Fecha y Hora</th>
                            <th>Salida</th>
                            <th>Destino</th>
                            <th>Vehículo</th>
                            <th>Conductor</th>
                            <th>Solicitante</th>
                            <th>Pasajeros</th>
                            <th>Precio base</th>
                            <th>Metodo de pago</th>
                            <th>Estatus</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in transfer %}
                            <tr>
                                <td class="text-center">{{ item.date|date:'d/m/Y'}}-{{ item.hour|date:'G:i' }}</td>
                                <td class="text-center">{{  item.rate.route.departure_point.name }}</td>
                                <td class="text-center">{{  item.rate.route.arrival_point.name }}</td>
                                <td class="text-center">
                                    {% if item.user_driver and item.user_driver.type %}
                                        {{ item.user_driver.type.type }}
                                    {% else %}
                                        <span class="text-muted">Sin vehículo</span>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if item.user_driver and item.user_driver.user %}
                                        {% if item.user_driver.user.first_name or item.user_driver.user.last_name %}
                                            {{ item.user_driver.user.first_name }} {{ item.user_driver.user.last_name }}
                                        {% else %}
                                            {{ item.user_driver.user.username }}
                                        {% endif %}
                                    {% else %}
                                        <span class="text-muted">Sin conductor</span>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if item.primary_person %}
                                        Traslado {{ item.primary_person.name }}
                                    {% else %}
                                        {% with persons=item.person_to_transfer.all %}
                                            {% if persons %}
                                                {% for p in persons|slice:":1" %}
                                                    Traslado {{ p.name }}
                                                {% endfor %}
                                            {% else %}
                                                <span class="text-muted">Sin personas</span>
                                            {% endif %}
                                        {% endwith %}
                                    {% endif %}
                                </td>
                                <td class="text-center">{{ item.person_to_transfer.all|length }}</td>
                                <td class="text-center">{{ item.rate.price }}$</td>
                                <td class="text-center">{{ item.get_payment_method_display }}</td>
                                <td class="text-center">
                                    <span class="d-inline-block position-relative ms-2">
                                        <!--begin::Label-->
                                        <span class="d-inline-block mb-2 fs-1tx fw-bolder">
                                            {{ item.status|title }}
                                        </span>
                                        {% if item.status == 'esperando validacion' %}
                                        <span class="d-inline-block position-absolute h-8px bottom-0 end-0 start-0 bg-warning translate rounded"></span>
                                        {% elif item.status == 'validada' %}
                                        <span class="d-inline-block position-absolute h-8px bottom-0 end-0 start-0 bg-primary translate rounded"></span>
                                        {% elif item.status == 'aprobada' %}
                                        <span class="d-inline-block position-absolute h-8px bottom-0 end-0 start-0 bg-success translate rounded"></span>
                                        {% elif item.status == 'en proceso' %}
                                        <span class="d-inline-block position-absolute h-8px bottom-0 end-0 start-0 bg-info translate rounded"></span>
                                        {% elif item.status == 'finalizada' %}
                                        <span class="d-inline-block position-absolute h-8px bottom-0 end-0 start-0 bg-success translate rounded"></span>
                                        {% endif %}
                                        <!--end::Line-->
                                    </span>
                                </td>
                                <td class="text-end">
                                    <a href="#" class="btn btn-light btn-active-light-primary btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Acciones
                                    <!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
                                    <span class="svg-icon svg-icon-5 m-0">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                            <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor" />
                                        </svg>
                                    </span>
                                    <!--end::Svg Icon--></a>
                                    <!--begin::Menu-->
                                    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" data-kt-menu="true">
                                        <!--end::Menu item-->
                                        <!--begin::Menu item-->
                                        <!-- <div class="menu-item px-3">
                                            <a href="#" class="menu-link px-3" data-kt-users-table-filter="delete_row">Eliminar</a>
                                        </div> -->
                                        
                                        <div class="menu-item px-3">
                                            <a href="{% url 'core:transfer_request_detail' pk=item.id %}" class="menu-link px-3" data-kt-users-table-filter="delete_row">Ver</a>
                                        </div>
                                        
                                        <div class="menu-item px-3">
                                            <a href="{% url 'core:transfer_request_update' pk=item.id %}" class="menu-link px-3">Editar</a>
                                        </div>

                                        <div class="menu-item px-3 pt-xl-1">
                                            <a href="#" class="btn btn-xs btn-danger cancelar" data-id="{{ item.id }}">Cancelar</a>
                                        </div>
                                        <!--end::Menu item-->
                                    </div>
                                    <!--end::Menu-->
                                </td>
                                <!-- <td></td> -->
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>    
                <!--end::Table-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Category-->
    </div>
    <!--end::Container-->
</div>
{% endblock content %} 

{% block extra_js %} 
    <script>
    let url_approve_ajax = "{% url 'core:transfer_request_approve' %}";
    let url_approve_ajax_admin = "{% url 'core:transfer_request_approve_admin' %}";
    let url_cancel_ajax = "{% url 'core:transfer_request_cancel' %}";
    </script>   
    <script src="{% static 'trasnfer_request_list.js' %}"></script>
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
{% endblock extra_js %}

templates/loyal_ryde_system/trips/trips_progress.html
{% extends "loyal_ryde_system/base/base.html" %}
{% load static %}

{% block title %}Lista de Viajes{% endblock title %}

{% block extra_css %}
<link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
{% endblock extra_css %}

{% block content %}
<div class="post d-flex flex-column-fluid" id="kt_post" data-aos="fade-up">
    <div id="kt_content_container" class="container-xxl">
        <div class="card card-flush">
            <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                <div class="col-md-12 text-center">
                    <h1 class="">Lista de Viajes: En progreso</h1>
                </div>
                <div class="card-title">
                    <div class="d-flex align-items-center position-relative my-1">
                        <span class="svg-icon svg-icon-1 position-absolute ms-4">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                            </svg>
                        </span>
                        <input type="text" data-kt-ecommerce-category-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Buscar viaje" />
                    </div>
                </div>
                <div class="card-toolbar">
                    <a href="{% url 'core:rates_departure_create' %}" class="btn btn-primary">Añadir salida</a>
                </div>
            </div>
            <div class="card-body pt-0">
                <table class="table align-middle table-row-dashed fs-6 gy-5" id="trips_progress_table">
                    <thead>
                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                            <th>Fecha y Hora</th>
                            <th>Salida</th>
                            <th>Destino</th>
                            <th>Vehículo</th>
                            <th>Conductor</th>
                            <th>Solicitante</th>
                            <th>Pasajeros</th>
                            <th>Precio base</th>
                            <th>Metodo de pago</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="fw-bold text-gray-600">
                        {% for item in transfer %}
                        <tr>
                            <td class="text-center">{{ item.date|date:'d/m/Y'}}-{{ item.hour|date:'G:i' }}</td>
                            <td class="text-center">{{  item.rate.route.departure_point.name }}</td>
                            <td class="text-center">{{  item.rate.route.arrival_point.name }}</td>
                            <td class="text-center">
                                {% if item.user_driver and item.user_driver.type %}
                                    {{ item.user_driver.type.type }}
                                {% else %}
                                    <span class="text-muted">Sin vehículo</span>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if item.user_driver and item.user_driver.user %}
                                    {% if item.user_driver.user.first_name or item.user_driver.user.last_name %}
                                        {{ item.user_driver.user.first_name }} {{ item.user_driver.user.last_name }}
                                    {% else %}
                                        {{ item.user_driver.user.username }}
                                    {% endif %}
                                {% else %}
                                    <span class="text-muted">Sin conductor</span>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if item.primary_person %}
                                    Traslado {{ item.primary_person.name }}
                                {% else %}
                                    {% with persons=item.person_to_transfer.all %}
                                        {% if persons %}
                                            {% for p in persons|slice:":1" %}
                                                Traslado {{ p.name }}
                                            {% endfor %}
                                        {% else %}
                                            <span class="text-muted">Sin personas</span>
                                        {% endif %}
                                    {% endwith %}
                                {% endif %}
                            </td>
                            <td class="text-center">{{ item.person_to_transfer.all|length }}</td>
                            <td class="text-center">{{ item.rate.price }}$</td>
                            <td class="text-center">{{ item.get_payment_method_display }}</td>
                            <td class="text-end">
                                <div class="dropdown">
                                    <button class="btn btn-light btn-sm dropdown-toggle" type="button" id="dropdownMenuButton{{ item.id }}" data-bs-toggle="dropdown" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton{{ item.id }}">
                                        <li><a class="dropdown-item" href="{% url 'core:transfer_request_detail' pk=item.id %}">Ver</a></li>
                                        <li><a class="dropdown-item" href="{% url 'core:transfer_request_update' pk=item.id %}">Editar</a></li>
                                        <li><a class="dropdown-item cancelar" href="#" data-id="{{ item.id }}">Cancelar</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %} 
    <script>
    let url_approve_ajax = "{% url 'core:transfer_request_approve' %}";
    let url_approve_ajax_admin = "{% url 'core:transfer_request_approve_admin' %}";
    let url_cancel_ajax = "{% url 'core:transfer_request_cancel' %}";
    </script>   
    
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
    <script src="{% static 'trasnfer_request_list.js' %}"></script>
{% endblock extra_js %}